name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build --file ./ArtistApi/Dockerfile --tag brightstraining24fall.azurecr.io/morby/artistapi:latest .

      # Step 3: Log in to Azure using Service Principal
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.DEPLOYMENT_CREDENTIALS }}

      # Step 4: Log in to Azure Container Registry (ACR)
      - name: Log in to ACR
        run: |
          az acr login --name brightstraining24fall

      # Step 5: Push the Docker image to ACR
      - name: Push the Docker image to ACR
        run: |
          docker push brightstraining24fall.azurecr.io/morby/artistapi:latest

      # Optional Step 6: Deploy the container to Azure Container Apps
      # Uncomment if you want to deploy the image to Azure Container Apps
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          resource-group: rg-mho-brights-01
          app-name: ca-mho-brights-01
          imageToDeploy: brightstraining24fall.azurecr.io/morby/artistapi:latest
