name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build --file ./ArtistApi/Dockerfile --tag brightstraining24fall.azurecr.io/morby/artistapi:$(date +%s) .

      # Step 3: Login to ACR
     # Step 3: Login to ACR
      - name: Log in to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login brightstraining24fall.azurecr.io --username "${{ secrets.ACR_USERNAME }}" --password-stdin

      # Step 4: Push the Docker image to ACR
      - name: Push the Docker image to ACR
        run: |
          docker push brightstraining24fall.azurecr.io/morby/artistapi:$(date +%s)
