name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Run Integration Tests
      - name: Run Integration Tests
        run: dotnet test ./ArtistApi.Test/ArtistApi.Test.csproj # Adjust the path to your test project

      # Step 3: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build --file ./ArtistApi/Dockerfile --tag brightstraining24fall.azurecr.io/morby/artistapi .

      # Debugging Secrets Length
      - name: Debugging Secrets
        run: |
          echo "ACR_USERNAME length: ${#ACR_USERNAME}"
          echo "ACR_PASSWORD length: ${#ACR_PASSWORD}"
        env:
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

      # Step 4: Login to ACR
      - name: Log in to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login brightstraining24fall.azurecr.io --username "${{ secrets.ACR_USERNAME }}" --password-stdin

      # Step 5: Push the Docker image to ACR
      - name: Push the Docker image to ACR
        run: |
          docker push brightstraining24fall.azurecr.io/morby/artistapi

      # Step 6: Login to Azure
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ fromJson(secrets.DEPLOYMENT_CREDENTIALS).clientId }}
          client-secret: ${{ fromJson(secrets.DEPLOYMENT_CREDENTIALS).clientSecret }}
          tenant-id: ${{ fromJson(secrets.DEPLOYMENT_CREDENTIALS).tenantId }}
          subscription-id: ${{ fromJson(secrets.DEPLOYMENT_CREDENTIALS).subscriptionId }}

      # Step 7: Deploy to Azure Container Apps
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          app-name: ca-mho-brights-01  # Replace with your actual Container App name
          image: brightstraining24fall.azurecr.io/morby/artistapi  # The Docker image you just built
          cpu: 0.5  # Optional CPU allocation
          memory: 1Gi  # Optional memory allocation

      # Step 8: Verify that your Container App is updated
      - name: Verify Deployment
        run: |
          az containerapp show --name ca-mho-brights-01 --resource-group rg-bjo-brightscourse-01
