name: Hello World Workflow

# Trigger the workflow on any push to the repository
on: [push]

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out your repository code

    - name: Print Hello World
      run: echo "Hello, World!"
